---
# Turn the logging level to debug
debug: true

# Server relative configuration
server:
    # port for running the server
    read_port: 8080
    
    # interface to run the server
    read_interface: 0.0.0.0

    # port for running the server
    write_port: 9080
    
    # interface to run the server
    write_interface: 0.0.0.0

    # how many threads to run io_service
    numThreads: 1

# Lite comet relative configuration
lite_comet:
    NO_OFFSET: 0
    WAITING_DATA: -1
    NEEDS_RESYNC: -3

    CHANNEL_TIMEOUT: 10000
    CHANNEL_MAX_MSG: 20

    CLEANUP_CYCLE: 5000
...
